config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls", namespace="main_app")),
    path("expance", include("expance.urls", namespace="expance_app"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView
from .views import  (StatisicsView,LoginView, ProvincesView, 
                     ProvinceDetailView, RegionDetailView, SaleView, 
                     SaleDetailView, GetRegionsView, GetShopsView, ShopDetailView, 
                     StorageView, ProductsView,StorageHistoryView,ProductGetView,SaleItemView, DebtView, 
                     SaleGetView, Barcode, barcode_image, SettingsView)

app_name = "main_app"

urlpatterns = [
    path("statistics/", StatisicsView.as_view(), name="main"),
    path('barcode_image/<int:barcode_id>/', barcode_image, name='barcode_image'),
    path("provinces/", ProvincesView.as_view(), name="provinces"),
    path("province/<int:pk>/regions/", ProvinceDetailView.as_view(), name="province_detail"),
    path("regions/<int:pk>/shops/", RegionDetailView.as_view(), name="region_detail"),
    path('get-regions/', GetRegionsView.as_view(), name='get_regions'),
    path('get-shops/', GetShopsView.as_view(), name='get_shops'),
    
    path("sale/", SaleView.as_view(), name="sale"),
    path("sale/<int:pk>/", SaleDetailView.as_view(), name="sale_detail"),
    path("sale/get/<int:pk>/", SaleGetView.as_view(), name="sale_get"),
    path("sale/item/<int:pk>", SaleItemView.as_view(), name="sale_item_get"),
    path("shop/<int:pk>/", ShopDetailView.as_view(), name="shop_detail"),
  
    
    path("storage/", StorageView.as_view(), name="storage"),
    path("debt/", DebtView.as_view(), name="debt"),
    path("storage/products/", ProductsView.as_view(), name="products"),
    path("barcodes/", Barcode.as_view(), name="barcode"),
    path("storage/history/", StorageHistoryView.as_view(), name="storage_history"),
    path('storage/products/<int:pk>', ProductGetView.as_view(), name='product_get'),
    
    
    path('settings/', SettingsView.as_view(), name='settings_app'),
    
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

templates/markets/provinces.html
{% extends 'wrapper.html' %}
{% block title %}Do'konlar{% endblock title %}
{% block content %}
<style>
  table {
    overflow: auto;
  }
  
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  
  .card {
    margin: 10px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);
    background-color: #f8f9fa;
  }
  .card .card-body{
    display: flex;
    padding-top: 20px;
    justify-content: center;
    align-items: center;
    color: black;
    font-weight: 700;
  }
</style>
<div class="row">
    {% for i in object_list %}
    <div class="card" style="width: 18rem;">
        <a href="{% url 'main_app:province_detail' i.id %}">
          <div class="card-body">
            {{ i }}
          </div>
        </a>
      </div>
    {% endfor %}
</div>
{% endblock content %}

templates/markets/regions.html
{% extends 'wrapper.html' %}
{% block title %}Do'konlar{% endblock title %}
{% block content %}
<style>
  table {
    overflow: auto;
  }
  
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  
  .card {
    margin: 10px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);
    background-color: #f8f9fa;
  }
  .card .card-body{
    display: flex;
    padding-top: 20px;
    justify-content: center;
    align-items: center;
    color: black;
    font-weight: 700;
  }
  .msg{
    text-align: center;
    color: red;
    font-weight: 700;
  }
</style>
<div class="row">
  {% if province.regions.all %}
    {% for i in province.regions.all %}
    <div class="card" style="width: 18rem;">
        <a href="{% url 'main_app:region_detail' i.id %}">
            <div class="card-body">
                {{ i.name }}
            </div>
        </a>
    </div>
    {% endfor %}
  {% else %}
    <div class="msg">
      {{ province.name }} viloyatida hech qanday Tuman mavjud emas!!!<br>
    </div>
   <h4 style="margin-top: 100px;">Do'kon qo'shish uchun ko'rsatma</h4>
    <ol>
      <li>Sozlamalar bo'limiga o'tasiz</li>
      <li>Tuman qo'shish Formasini to'ldirib tasdiqlash tugmasini bosasiz</li>
    </ol>
  {% endif %}
</div>
{% endblock content %}

templates/markets/shop_detail.html
{% extends 'wrapper.html' %}
{% load humanize %}
{% block title %}{{ shop.name }} {{ shop.last_name}}{% endblock title %}
{% block content %}
<style>
  table {
    overflow: auto;
  }
  
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  
  .card {
    margin: 10px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);
    background-color: #f8f9fa;
  }
  .card .card-body{
    display: flex;
    padding-top: 20px;
    justify-content: center;
    align-items: center;
    color: black;
    font-weight: 700;
  }
  .msg{
    text-align: center;
    color: red;
    font-weight: 700;
  }
</style>
<div class="d-flex justify-content-between align-items-center">
    <div>
        <div class="d-felx justify-content-center align-items-center flex-column">
            <form method="POST" class="d-flex gap-2 justify-content-center align-items-center flex-column flex-lg-row justify-content-lg-start">
              {% csrf_token %}
             <div class="from">
              <input name="from" type="date" id="from" style="border-radius: 3px;margin-top:10px;outline:none;border:none;padding:10px 10px;">
             </div>
              <div class="till">
                <input name="till" type="date" id="from" style="border-radius: 3px;margin-top:10px;outline:none;border:none;padding:10px 10px;">
              </div>
              <div class="button pt-2">
                <button class="btn btn-primary" name="filtr" style="margin-left: 10px;">filtrlash</button>
              </div>
            </form>
          </div>
    </div>
    <div>
      <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-info" name="pdf">.pdf</button>
      </form>
    </div>
  </div>
<div class="row mt-3">
    {% if object_list %}
    <table class="table" >
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Ismi</th>
        <th scope="col">To'lov</th>
        <th scope="col">Qarz</th>
        <th scope="col">Jami summasi</th>
        <th scope="col">Sanasi</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for i in object_list %}
      <tr>
        <th scope="row">{{ i.id }}</th>
        <td><a href="{% url 'main_app:sale_detail' i.id %}">{{ i.shop.name }} {{ i.shop.last_name }}</a></td> 
        <td><a href="{% url 'main_app:sale_detail' i.id %}">{{ i.payment|intcomma }} UZS</a></td>                  
        <td><a href="{% url 'main_app:sale_detail' i.id %}">{{ i.debt|intcomma }} UZS</a></td>
        <td><a href="{% url 'main_app:sale_detail' i.id %}">{{ i.get_amount }}UZS</a></td>
        <td><a href="{% url 'main_app:sale_detail' i.id %}">{{ i.date_added.month }}/{{ i.date_added.day }}/{{ i.date_added.year }}</a></td>
          <td>
            <form method="POST" class="d-flex justify-content-start align-items-center gap-3">
              {% csrf_token %}
              <input type="hidden" name="sale" value="{{ i.id }}">
              <button type="button" class="btn btn-success edit-btn" data-id="{{ i.id }}" data-bs-toggle="modal"  data-bs-target="#editExpance"> <i class="bi bi-pen"></i></button>
            </form>
          </td>

      </tr>
      {% endfor %}
    </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&laquo;</span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                </li>
            {% endif %}
    
            {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link">&raquo;&raquo;</span>
                </li>
            {% endif %}
        </ul>
      </nav>
    {% else %}
    <div style="color: gray;font-size:20px;text-align:center">
        Bu do'kon hali savdo qilgani yo'q!!!
    </div>
    {% endif %}
</div>
<div class="row">
    <div class="card">
        Qarzdorligi - {{ debt }}
    </div>
</div>
<div class="modal fade" id="editExpance" tabindex="-1" aria-labelledby="editProductModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Sotuvni tahrirlash</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" value="sale_id" name="sale" id="sale_id">
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">To'lov:</label>
                <input type="number" class="form-control" id="name"  name="payment" required>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
              <button type="submit" class="btn btn-primary" name="save">Saqlash</button>
            </div>
          </form>
      </div>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $(".edit-btn").click(function() {
        var saleId = $(this).data("id");
        var csrfToken = "{{ csrf_token }}";

        // Set the sale ID in the hidden input
        $('#sale_id').val(saleId);
      })
});
</script>
{% endblock content %}

templates/markets/shops.html
{% extends 'wrapper.html' %}
{% block title %}Do'konlar{% endblock title %}
{% block content %}
<style>
  table {
    overflow: auto;
  }
  
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  
  .card {
    margin: 10px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);
    background-color: #f8f9fa;
  }
  .card .card-body{
    display: flex;
    padding-top: 20px;
    justify-content: center;
    align-items: center;
    color: black;
    font-weight: 700;
  }
  .msg{
    text-align: center;
    color: red;
    font-weight: 700;
  }
</style>
<div class="row">
  {% if region.shops.all %}
    {% for i in region.shops.all %}
    <div class="card" style="width: 18rem;">
        <a href="{% url 'main_app:shop_detail' i.id %}">
          <div class="card-body">
            {{ i.name }} {{ i.last_name }}
          </div>
        </a>
      </div>
    {% endfor %}
    {% else %}
    <div class="msg">
      {{ region.name }} viloyatida hech qanday Do'kon mavjud emas!!!<br>
    </div>
   <h4 style="margin-top: 100px;">Do'kon qo'shish uchun ko'rsatma</h4>
    <ol>
      <li>Sozlamalar bo'limiga o'tasiz</li>
      <li>Do'kon qo'shish Formasini to'ldirib tasdiqlash tugmasini bosasiz</li>
    </ol>
  {% endif %}
</div>
{% endblock content %}