config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls", namespace="main_app")),
    path("expance", include("expance.urls", namespace="expance_app"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

expance/urls.py
from django.urls import path
from .views import ExpanceView
app_name = "expance_app"

urlpatterns = [
    path("", ExpanceView.as_view(), name="expance")
]

main_app/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView
from .views import  (StatisicsView,LoginView, ProvincesView, 
                     ProvinceDetailView, RegionDetailView, SaleView, 
                     SaleDetailView, GetRegionsView, GetShopsView, ShopDetailView, 
                     StorageView, ProductsView,StorageHistoryView,ProductGetView,SaleItemView, DebtView, 
                     SaleGetView, Barcode, barcode_image, SettingsView)

app_name = "main_app"

urlpatterns = [
    path("statistics/", StatisicsView.as_view(), name="main"),
    path('barcode_image/<int:barcode_id>/', barcode_image, name='barcode_image'),
    path("provinces/", ProvincesView.as_view(), name="provinces"),
    path("province/<int:pk>/regions/", ProvinceDetailView.as_view(), name="province_detail"),
    path("regions/<int:pk>/shops/", RegionDetailView.as_view(), name="region_detail"),
    path('get-regions/', GetRegionsView.as_view(), name='get_regions'),
    path('get-shops/', GetShopsView.as_view(), name='get_shops'),
    
    path("sale/", SaleView.as_view(), name="sale"),
    path("sale/<int:pk>/", SaleDetailView.as_view(), name="sale_detail"),
    path("sale/get/<int:pk>/", SaleGetView.as_view(), name="sale_get"),
    path("sale/item/<int:pk>", SaleItemView.as_view(), name="sale_item_get"),
    path("shop/<int:pk>/", ShopDetailView.as_view(), name="shop_detail"),
  
    
    path("storage/", StorageView.as_view(), name="storage"),
    path("debt/", DebtView.as_view(), name="debt"),
    path("storage/products/", ProductsView.as_view(), name="products"),
    path("barcodes/", Barcode.as_view(), name="barcode"),
    path("storage/history/", StorageHistoryView.as_view(), name="storage_history"),
    path('storage/products/<int:pk>', ProductGetView.as_view(), name='product_get'),
    
    
    path('settings/', SettingsView.as_view(), name='settings_app'),
    
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

expance/models.py
from django.db import models


class Expances(models.Model):
    name = models.CharField(max_length=250)
    amount = models.PositiveIntegerField(default=0)
    date_added = models.DateField()
    
    def __str__(self):
        return self.name

expance/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Expances
from print_funcs import pdf_generator
from django.core.paginator import Paginator

class ExpanceView(ListView):
    template_name = "expances/expances.html"
    model = Expances
    paginate_by = 10
    context_object_name = 'object_list'
    
    def get_queryset(self):
        # Return the base queryset
        return Expances.objects.all()
    
    def get_context_data(self, **kwargs):
        context = {}
        sale_items = Expances.objects.all()
        paginator_sale_items = Paginator(sale_items, self.paginate_by)
        page_number_sale_items = self.request.GET.get('page_sale_items')
        page_obj_sale_items = paginator_sale_items.get_page(page_number_sale_items)
        context = {
            "object_list" : page_obj_sale_items
        }
        return context
    
    def post(self, request):
        queryset = self.get_queryset()
        context = self.get_context_data()
        if 'filtr' in request.POST:
            from_date = request.POST.get('from')
            till_date = request.POST.get('till')
            if from_date and till_date:
                queryset = queryset.filter(date_added__range=[from_date, till_date])
            context["object_list"] = queryset
            return render(request, self.template_name, context)

        elif 'add' in request.POST:
            obj = Expances.objects.create(
                name=request.POST.get("name"),
                amount=request.POST.get("amount"),
                date_added=request.POST.get("date")
            )
            return redirect("expance_app:expance")

        elif 'delete' in request.POST:
            # Handle deleting
            expance_id = request.POST.get('expance')
            Expances.objects.filter(id=expance_id).delete()
            return redirect("expance_app:expance")
        elif 'pdf' in request.POST:
            # Handle PDF generation
            return pdf_generator.generate_pdf(request, queryset)
        return render(request, self.template_name, context)

templates/index.html
{% extends "wrapper.html" %}
{% load static %}
{% block title %}Statistika{% endblock title %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="pagetitle">
  <h1>Statistika</h1>
</div><!-- End Page Title -->

<section class="section dashboard">
  <div class="row">
    <!-- Your JavaScript code here --><!-- End Left side columns -->
    <div class="col-lg-12">
      <div class="row">
        <!-- Sales Card -->
        <div class="col-xxl-3 col-md-6">
          <div class="card info-card sales-card">
            <div class="card-body">
              <h5 class="card-title">Sotuv <span>| Shu oyda</span></h5>

              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-cart"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ sale_month }} so'm</h6>
                </div>
              </div>
            </div>

          </div>
        </div><!-- End Sales Card -->

        <!-- Revenue Card -->
        <div class="col-xxl-3 col-md-6">
          <div class="card info-card revenue-card">
            <div class="card-body">
              <h5 class="card-title">Foyda <span>| Shu oyda</span></h5>

              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-currency-dollar"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ income_month }} so'm</h6>
                </div>
              </div>
            </div>

          </div>
        </div><!-- End Revenue Card -->

        <div class="col-xxl-3 col-md-6">

          <div class="card info-card customers-card">
            <div class="card-body">
              <h5 class="card-title">Eng Ko'p sotilgan Mahsulot <span>| Shu oyda</span></h5>

              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-box-fill"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ most_sold_product }}</h6>
                </div>
              </div>

            </div>
          </div>

        </div>
        <!-- Customers Card -->
        <div class="col-xxl-3 col-md-6">

          <div class="card info-card customers-card">
            <div class="card-body">
              <h5 class="card-title">Eng Ko'p xarid qilgan mijoz <span>| Shu oyda</span></h5>

              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-people"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ most_bought_shop }}</h6>
                </div>
              </div>

            </div>
          </div>

        </div><!-- End Customers Card -->
      </div>
      <div class="row">
          <div class="col-xxl-12 card">
            <div id="salesChartContainer" height="200px">
              <canvas id="monthlySalesChart" width="1000" height="200"></canvas>
              <script>
                const monthNames = {{ month_names|safe }};
                const sales = {{ sales|safe }};
              
                const monthlySalesChart = document.getElementById('monthlySalesChart').getContext('2d');
                const chart = new Chart(monthlySalesChart, {
                    type: 'bar', // Bar chart
                    data: {
                        labels: monthNames,
                        datasets: [{
                            label: 'Sales Quantity',
                            data: sales,
                            backgroundColor: 'rgba(75, 192, 192, 0.2)',
                            borderColor: 'rgba(75, 192, 192, 1)',
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });
              </script>
            </div>
          </div>
      </div>
      
    </div>
  </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% endblock content %}

templates/qr_codes.html
{% extends 'wrapper.html' %}
{% load humanize %}
{% block title %}Barcodes{% endblock title %}
{% block content %}
<style>
  table{
    overflow: auto;
  }
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  .product_a{
    margin-right: 10px;
    background-color: white;
    color: black;
  }
  #scannerInput {
        position: absolute;
        top: -9999px;
    }
</style><!-- End Page Title -->
<h1>BarCode lar</h1>
  <div class="d-flex justify-content-end align-items-center">
    <div>
      <form method="POST">
        {% csrf_token %}
        <button type="button" class="btn btn-success" id="startScanButton">Qo'shish</button>
      </form>
    </div>
  </div>
  {% if messages %}
<ul class="messages text-center mt-10" style="color: red;">
    {% for message in messages %}
    <h1{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h1>
    {% endfor %}
</ul>
{% endif %}
<div id="reader" style="display: none;"></div>
    <div class="row mt-4" style="overflow-x: auto;"> 
      {% if page_obj_products %}
            <table class="table" >
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Kod</th>
                  <th scope="col">Action</th>
                  <th scope="col">Print</th>
                </tr>
              </thead>
              <tbody>
                {% for i in page_obj_products %}
                <tr>
                  <th scope="row">{{ i.id }}</th>
                  <td>{{ i.number }}</td>
                  <td><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModel{{ i.id }}">O'chirish</button></td>
                  <td><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#printModal{{ i.id }}">Print</button></td>
                </tr>
                <div class="modal fade" id="printModal{{ i.id }}" tabindex="-1" aria-labelledby="printModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h1 class="modal-title fs-5" id="printModalLabel">Print Barcode</h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <img src="{% url 'main_app:barcode_image' barcode_id=i.id %}" alt="Barcode" id="barcodeImage{{ i.id }}" class="img-fluid">
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary" onclick="printBarcode('barcodeImage{{ i.id }}')">Print</button>
                        </div>
                      </div>
                    </div>
                  </div>
                <div class="modal fade" id="deleteModel{{ i.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-body">
                            O'chirishni Tasdiqlash
                          <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ i.id }}" name="ID">
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                              <button type="submit" class="btn btn-danger" name="delete">O'chirish</button>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
              <div style="color: gray;font-size:20px;text-align:center">
                Ma'lumot mavjud emas!!!
              </div>
            {% endif %}
            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center">
                {% if page_obj_products.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page_products={{ page_obj_products.previous_page_number }}">Oldingi</a></li>
                {% endif %}
                {% for num in page_obj_products.paginator.page_range %}
                  {% if page_obj_products.number == num %}
                    <li class="page-item active"><a class="page-link" href="?page_products={{ num }}">{{ num }}</a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page_products={{ num }}">{{ num }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj_products.has_next %}
                  <li class="page-item"><a class="page-link" href="?page_products={{ page_obj_products.next_page_number }}">Keyingi</a></li>
                {% endif %}
              </ul>
            </nav>
    </div>
<div class="modal fade" id="scanModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">QrCode Qo'shish</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">ID:</label>
            <input type="text" class="form-control" id="productID"  name="ID" required>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
            <button type="submit" class="btn btn-primary" name="add">Saqlash</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.8/html5-qrcode.min.js" integrity="sha512-r6rDA7W6ZeQhvl8S7yRVQUKVHdexq+GAlNkNNqVC7YyIV+NwqCTJe2hDWCiffTyRNOeGEzRRJ9ifvRm/HCzGYg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  let html5QrCode;
  let scannerActive = false;

  document.getElementById('startScanButton').addEventListener('click', function() {
    if (!scannerActive) {
      html5QrCode = new Html5Qrcode("reader");

      html5QrCode.start(
        { facingMode: "environment" }, // Use rear camera
        {
          fps: 10, // Frames per second
          qrbox: { width: 250, height: 250 } // Size of the scanning box
        },
        onScanSuccess,
        onScanFailure
      ).catch(err => {
        console.error(`Error starting scanner: ${err}`);
      });

      document.getElementById('reader').style.display = 'block'; // Show the reader
      scannerActive = true;
    }
  });

  function onScanSuccess(decodedText, decodedResult) {
    // Handle the result here
    document.getElementById('productID').value = decodedText;

    // Stop scanning after the first successful scan
    if (scannerActive) {
      html5QrCode.stop().then(() => {
        console.log("QR code scanning stopped.");
        document.getElementById('reader').style.display = 'none'; // Hide the reader
        scannerActive = false;
        // Open the modal
        var scanModal = new bootstrap.Modal(document.getElementById('scanModal'));
        scanModal.show();
      }).catch(err => {
        console.error(`Error stopping scanner: ${err}`);
      });
    }
  }

  function onScanFailure(error) {
    // Handle scan failure
    console.error(`Scan error: ${error}`);
  }
</script>
<script>
    function printBarcode(imageId) {
      const printWindow = window.open('', '', 'width=800,height=600');
      const image = document.getElementById(imageId).src;
      printWindow.document.write('<html><head><title>Print Barcode</title></head><body>');
      printWindow.document.write('<img src="' + image + '" style="width: 100%;">');
      printWindow.document.write('</body></html>');
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  </script>
{% endblock content %}

templates/shops.html
{% extends 'wrapper.html' %}
{% block title %}Do'konlar{% endblock title %}
{% block content %}
<style>
  table {
    overflow: auto;
  }
  
  tr:hover {
    background-color: rgb(194, 190, 190);
  }
  
  .card {
    margin: 10px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 12px 16px rgba(0, 0, 0, 0.2);
    background-color: #f8f9fa;
  }
  .card .card-body{
    display: flex;
    padding-top: 20px;
    justify-content: center;
    align-items: center;
    color: black;
    font-weight: 700;
  }
  .msg{
    text-align: center;
    color: red;
    font-weight: 700;
  }
</style>
<div class="row">
  {% if region.shops.all %}
    {% for i in region.shops.all %}
    <div class="card" style="width: 18rem;">
        <a href="{% url 'main_app:province_detail' i.id %}">
          <div class="card-body">
            {{ i.name }} {{ i.last_name }}
          </div>
        </a>
      </div>
    {% endfor %}
    {% else %}
    <div class="msg">
      {{ region.name }} viloyatida hech qanday Do'kon mavjud emas!!!<br>
    </div>
   <h4 style="margin-top: 100px;">Do'kon qo'shish uchun ko'rsatma</h4>
    <ol>
      <li>Sozlamalar bo'limiga o'tasiz</li>
      <li>Do'kon qo'shish Formasini to'ldirib tasdiqlash tugmasini bosasiz</li>
    </ol>
  {% endif %}
</div>
{% endblock content %}

templates/wrapper.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %} {% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <style>
    .logo{
      color: red;
      font-weight: 900;
      font-size: 25px;
    }
  </style>
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'main_app:main' %}" class="logo d-flex align-items-center">
        Mtoys
        <span class="d-none d-lg-block"></span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="GET">
        <input type="text" name="query" placeholder="Qidiruv" title="Enter search keyword">
        <button type="submit" title="Search" name="search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->
        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/Sample_User_Icon (1).png' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.username }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Foydalanuvchi nomi</h6>
              <span>{{ request.user.username }}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="https://t.me/Saidjalol10">
                <i class="bi bi-question-circle"></i>
                <span>Yordam</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a id="logout-link_nav" class="dropdown-item d-flex align-items-center" href="{% url 'main_app:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Chiqish</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:main'%}">
          <i class="bi bi-grid"></i>
          <span>Statistika</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:provinces'%}">
          <i class="bi bi-shop"></i>
          <span>Do'konlar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:sale'%}">
          <i class="bi bi-receipt"></i>
          <span>Sotuv</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:debt'%}">
          <i class="bi bi-credit-card-2-back"></i>
          <span>Qarzdorlik</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'expance_app:expance'%}">
          <i class="bi bi-cash-coin"></i>
          <span>Chiqimlar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:storage'%}">
          <i class="bi bi-house-door-fill"></i>
          <span>Ombor</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:barcode'%}">
          <i class="bi bi-upc-scan"></i>
          <span>Barcodelar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:settings_app'%}">
          <i class="bi bi-gear"></i>
          <span>Sozlamalar</span>
        </a>
      </li>
      <li class="nav-heading">Qo'shimcha Kategoriyalar</li><!-- End Profile Page Nav -->
      <li class="nav-item">
        <a class="nav-link collapsed"  href="http://t.me/Saidjalol10">
          <i class="bi bi-question-circle"></i>
          <span>Yordam</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->
      

      <ul class="nav">
        <!-- Other nav items -->
        <li class="nav-item">
          <a id="logout-link" class="nav-link collapsed" href="#">
            <i class="bi bi-box-arrow-in-right"></i>
            <span>Chiqish</span>
          </a>
        </li>
      </ul>
      
      <!-- Hidden logout form -->
      <form id="logout-form" method="post" action="{% url 'main_app:logout' %}" style="display: none;">
        {% csrf_token %}
      </form>
      
      <script>
        document.getElementById('logout-link').addEventListener('click', function(event) {
          event.preventDefault();
          document.getElementById('logout-form').submit();
        });
        document.getElementById('logout-link_nav').addEventListener('click', function(event) {
          event.preventDefault();
          document.getElementById('logout-form').submit();
        });
      </script>
    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
        {% block content %} {% endblock content %}
  </main><!-- End #main -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>